apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: null
  name: vpnkit-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpnkit-controller
subjects:
- kind: ServiceAccount
  name: vpnkit-controller
  namespace: kube-system
