apiVersion: v1
kind: Secret
metadata:
    name: kube-dumper-token-l7hwj
    namespace: kube-dumper
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T21:43:53Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewED507HyPhNDZAMbUI7YT50AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfTjwL36nRpod/GzaAgEQgDutnNggGWz4ZxDJtWoTDXlznm4E3PiEZsp0Bch1KBslj/IJRHjsoN0HdQkjVjtZ7wgCEPP5mpMPvVwU2Q==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T21:43:54Z'
    mac: ENC[AES256_GCM,data:1uWVxWAHXcBPFjG0l3njFxLzqbXZ+AdtmyjMK9+FatXHMvdWYGxaqblJJdI//6Ym/HVJAU28SktuXiBPCk4h1zHYRIKl/ut8Eciqwl6iyV8nsHD+A56D3u//07bAZ/BSIywW9vZ9sO9mL/XtbsGjKk4EE22G2S8WOtpfgW4oowc=,iv:0TA7HBtELzMnzZ63wYVIx9Hzs7Rog4L5F5MJXUlawCM=,tag:XTxXBkDqLUneKO4SJthKCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
