apiVersion: v1
data:
  fieldFilters.yaml: |
    metadata:
      annotations:
        control-plane.alpha.kubernetes.io/leader:
        deployment.kubernetes.io/revision:
        deployment.kubernetes.io/revision-history:
        deployment.kubernetes.io/desired-replicas:
        deployment.kubernetes.io/max-replicas:
        kubectl.kubernetes.io/last-applied-configuration:
      creationTimestamp:
      deletionTimestamp:
      finalizers:
      generateName:
      generation:
      resourceVersion:
      selfLink:
      uid:
      labels:
        pod-template-hash:
      managedFields:
    spec:
      nodeName:
      renewTime:
    status:
kind: ConfigMap
metadata:
  annotations: null
  name: dump-files-9k656hf2f2
  namespace: kube-dumper
