apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  labels:
    app: kube-dumper
  name: kube-dumper
  namespace: kube-dumper
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-dumper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-dumper
      name: kube-dumper
      namespace: kube-dumper
    spec:
      containers:
      - env:
        - name: REPOSITORY_URL
          valueFrom:
            configMapKeyRef:
              key: REPOSITORY_URL
              name: kube-dumper
        - name: REFRESH_GVRS_TIME_IN_MINUTES
          valueFrom:
            configMapKeyRef:
              key: REFRESH_GVRS_TIME_IN_MINUTES
              name: kube-dumper
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_REGION
              name: aws
        image: inloco/kube-dumper
        imagePullPolicy: Never
        name: kube-dumper
        resources:
          requests:
            ephemeral-storage: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/dump-files
          name: dump-files
          readOnly: true
        - mountPath: /root/.ssh/id_rsa
          name: ssh
          readOnly: true
          subPath: id_rsa
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-dumper
      serviceAccountName: kube-dumper
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: dump-files-9k656hf2f2
        name: dump-files
      - name: ssh
        secret:
          defaultMode: 256
          secretName: ssh
