apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1beta1.rbac.authorization.k8s.io
spec:
  group: rbac.authorization.k8s.io
  groupPriorityMinimum: 17000
  version: v1beta1
  versionPriority: 12
