apiVersion: v1
kind: Pod
metadata:
  annotations: null
  labels:
    component: storage-provisioner
  name: storage-provisioner
  namespace: kube-system
spec:
  containers:
  - args:
    - /var/lib/k8s-pvs
    image: docker/desktop-storage-provisioner:v1.1
    imagePullPolicy: IfNotPresent
    name: storage-provisioner
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/k8s-pvs
      name: pvs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: storage-provisioner-token-2dqsr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: storage-provisioner
  serviceAccountName: storage-provisioner
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/lib/k8s-pvs
      type: Directory
    name: pvs
  - name: storage-provisioner-token-2dqsr
    secret:
      defaultMode: 420
      secretName: storage-provisioner-token-2dqsr
