apiVersion: v1
kind: Pod
metadata:
  annotations: null
  labels:
    component: vpnkit-controller
  name: vpnkit-controller
  namespace: kube-system
spec:
  containers:
  - command:
    - /kube-vpnkit-forwarder
    - -path
    - /run/host-services/backend.sock
    image: docker/desktop-vpnkit-controller:v1.0
    imagePullPolicy: IfNotPresent
    name: vpnkit-controller
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/host-services/backend.sock
      name: api
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vpnkit-controller-token-q9rjd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: vpnkit-controller
  serviceAccountName: vpnkit-controller
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /run/host-services/backend.sock
      type: ""
    name: api
  - name: vpnkit-controller-token-q9rjd
    secret:
      defaultMode: 420
      secretName: vpnkit-controller-token-q9rjd
