apiVersion: v1
kind: Secret
metadata:
    name: attachdetach-controller-token-bp5gs
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:31Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewFy6lDwVJHAIlWVIUWjQYA3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1NNR688xCMFxVSeaAgEQgDsGH+q0x+FxPE+Ux2BC2bTFQG0AgW6xQ8jiMnlBuZhfy34kAeafuUtAr4YIYveC5YuzWIQVkfy4BPDM1A==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:31Z'
    mac: ENC[AES256_GCM,data:ZL+B7Or5Q3zyMiASck+ygDr8bi3j7QJCe/tN12G9sdGKLkfaEYs59g2Gx64djzOA0T1+5MnmC2yBkMmWx8oTsHPD+/3eHnaZzz8B/HrBIOpD+o2WCy1/nr4iqYodnGeSFk/78H3ZP5P2v/MBBOLA1lWgdd27d2qE/vk23RXpxao=,iv:kG7v86afDH+Ywabr6DnwrA5oodXdB6JAGipNWfvtABo=,tag:VO2Ej1s4QR4h9NofYrFLoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
