apiVersion: v1
kind: Secret
metadata:
    name: coredns-token-ctgt5
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:31Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewF9uOyaaWsvvP5bm81IqzwOAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYUqC/HizMFxfq62oAgEQgDt/TzanA+R4gRAUpSoEhJY4wp+qpyqPARtJo8bHqG9pvxFqvXBMZD+r3sV/JIxChorYGFtBAHRaP/Ry9A==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:31Z'
    mac: ENC[AES256_GCM,data:45ujV+I+fLtoIhi+pQ6RcpPfs9sP0k4tgy09sQQfKMuYqaIgYC37XqeTJ39gHCUB4y0Wja6R0fQMHzLf4S8uvEUq7V9tqhbQUkagY80Pym6LPEAkvQf35UXjZUTg5aFmsXWvPZZLGRl4SOhaeS++bQgqm+hGSoPM1Yp/XcW9Qd0=,iv:V6b11kNqQlPz9EVTd4Ps589BjFGUPNBTyoHd80MGmoA=,tag:iiN1bktvlid0pNH+FWUuXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
