apiVersion: v1
kind: Secret
metadata:
    name: cronjob-controller-token-99xlb
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:31Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewHUdV9uNDxF6AHSmefSn+yAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4kGX1QygUsEK2iKWAgEQgDs2rI0GmiRkbnLxIKDF58cMccpkVhO3hqKhNeZv5CS9RnXaCNhEFja9qm2fF9XN0dL1zur7skZIWmEa3w==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:32Z'
    mac: ENC[AES256_GCM,data:EWzaT7F6LsVgPWmnWtHS1IG1tu1j5rIHhlWj+KamPLcW62VqTxA+tAjpzAiLpRyOVFlmH+D1LS562fg+QKGSsztWC6KyPSiF80ffgThX5S9+wH7mZoef6byTPB42pLiF5K9C2meoZLXxTnzzeh0JLbC2aP7EDvX4I6qEsMA4IMM=,iv:elhy0D757on6Io27Xl3RIY9KQjK0VUT4tRAoiXf8qVc=,tag:n/FK6IOYdUoL48uXWzlkzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
