apiVersion: v1
kind: Secret
metadata:
    name: default-token-mhvqz
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:32Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewE9uX4X3cPSIJINVvitGyHHAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQvaX73qDkJkWnJVLAgEQgDu+69tI34EIRWelR5+DN3p6bFpWVyaYWGWuFiInyyOdYHra+DztI7RUKfz+w2apCPnsD6Nm1hpkH0QbDw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:32Z'
    mac: ENC[AES256_GCM,data:mBzTHmo59gAFkTE29UgHwlUMSEq8JsIoAXwdwIfn5EqrSzV5L1sTGEikW4rtk4QyhPh3/rAPliYWworXsZb8RgBD/R4UgRbQPROmSDNiIjTXTQsLNJmPcRKFfTsChn+IZ//WxIo/hhceLdZkWbD5AxYTATAEhWPcjWfSUfarrgQ=,iv:7Y86N4B8PFahpBVHXgwfZwWGu6swu8nK+4THY/s/oSA=,tag:8qbDAVX2o0bMyTXaOLdP9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
