apiVersion: v1
kind: Secret
metadata:
    name: disruption-controller-token-t4bzx
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:32Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewGCAufiQ7KBPuPD2q9SebTYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFHCJ6eKH/LiY8HDCAgEQgDur0vp7bVbvIeu6de/BVRUNQYuZ799+n+s17y9knZR8fHd5erjWVOICz4Po6tba31uJzJnGowF6X5yoBQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:32Z'
    mac: ENC[AES256_GCM,data:3FjT27G6WdIZugXa5RSzODrg497ZU7D397ONdQtZ5F337TYGKXpTvRRpbIFT/1IGIRqkVjEHi1a/zOjY4bCIqcFAdUtVXQR//gSmCEDPBMs0R3YDGNLW4whlvZ6f3Mf2NTVzVbN0p1DnGTs1eVCDAmoTq8U3C6mus1qLlgZa/5Y=,iv:bTchCl24aWJtiotHxh3HKr3TOIIh+0GIHtZV3vgPs+I=,tag:2cQLcHWrNnE9lyZKPdCq6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
