apiVersion: v1
kind: Secret
metadata:
    name: endpointslicemirroring-controller-token-vkcwh
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:32Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewFC/tCMAepFIXx/6B605lR6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBp+mnWVrgt021cHMAgEQgDvb5YpwEGuLhYDA3On1SHFf7KGrD/9RKsGADMkmwsMTPgq8BnZi3qgOBrP4l09JtppMzVIPqT/C7mzdsQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:33Z'
    mac: ENC[AES256_GCM,data:2XsegTiFhXLJX9GJJ90mP55Z5d9Qwklqr6/5s0FI/vk1yktdXv44vqZoXN90g670ltZ3GN5o6ODCx+hL1R4eGYo7QkWkIbewHKlyjFxZEHIRvn+/i8Fcszf4vjz8PsuFUN0WsT8zjIrSemL5FDQDMD3VIkdwdWE2JGjVScbq1/U=,iv:ZNAcD4epTUiYkEMjMgkrpOxN8/oLK2pPAB6ErBnyjBw=,tag:un8MRkR/Zk9gGoUAsmb8Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
