apiVersion: v1
kind: Secret
metadata:
    name: kube-proxy-token-5lvz7
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:33Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewETP0sBJNnEjxboABAYZ6WmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQWsPDIqQRqL2JrpVAgEQgDs6fvPJ22ccOy8RwMBVqbmbr/wt4BZ08u/l+1W+7nCK4/LDSddiiRcfoXFHl3BBa5ZTkF2ZAg3ofzMYdQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:33Z'
    mac: ENC[AES256_GCM,data:krDyuTzbnTmzv2URkXQD2i4GDzAWIMDDpj4dAFs9KtC2/GamED+qBE1wFMfIzQZAAwCTIkv4hX5kN//KwlpMJlxbWGRgWv8QM/YAGQjfp7EV32HFa8XDjwdG6ey3XIg/8nJj/X3Fpej0slLQphCYi18d4nHvRAUfabN2CQS9RYM=,iv:OcpJgYSRbDxPFEcdfAx5tmnYfQuNH44mWaeD02PzcX4=,tag:BnghKaE3H3BCbUwR5/Nokw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
