apiVersion: v1
kind: Secret
metadata:
    name: pod-garbage-collector-token-6cwmc
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:34Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewExOVongMDQcByGEHazN7UPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMigSVMiE7hFxJE9WsAgEQgDtHbDY99z3fy5c2ohM8Su8jLvUN5tkkrWiZPnxTZjhf5pec4KzOFeqvqBwXNr2NGkffK7BkuYzQ1B9RrQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:34Z'
    mac: ENC[AES256_GCM,data:mPh0Kf+irjlSNc2IVH+lQ3twhIdUYP5h48iFZk7DFkhzbVVXbbfursa4K74cDqgCiqgG/l66YYI7JXGDdf2jcZoT1kHNnXpyFGFiOFBQXtgRcZqpVBJhINOKa0z90Hy+wPkfT0FSp6SMpTyf8GPUtoP7kbALEmNpxtHfW5sCSLI=,iv:KLIMoQ+7VKi3VQth8iin/1m41CxoyV0nBUBsMQCswy8=,tag:unqIhOYTPgM6LstWWogzow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
