apiVersion: v1
kind: Secret
metadata:
    name: pv-protection-controller-token-rlcfj
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:34Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewEa7icwHlyESsaGir1ldIMTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQrV8kQjgklF3LziLAgEQgDvIeZfz1nAD6aSjEBSkS5JfmKjJChP6818n4DsS3jKbt/k0u88D9Tt01s3By0P8KrriDR8nh3TzpqPfqQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:34Z'
    mac: ENC[AES256_GCM,data:Q5g8G1YFJU0vdXk1Yfocc09g4yeZBXFdKvrv1gkgE7oZw2Ia1AJQ6cHLd2V0cba/uuh7lZuWQqjV5q2PWckj15sCtrhUiZvb9jOYq2jB+WikogJveMKjRyS02TpEhGAXGtduI0CSJ24ftquDzAACyZjOgqqOJtv7QKzXtMKlnRk=,iv:hjFnKbtXLqeAF12jvx/r2tC6CX/MQwIndlrqtVyMfv8=,tag:43Rj+srt9sUG7tjuZjH9IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
