apiVersion: v1
kind: Secret
metadata:
    name: resourcequota-controller-token-2hs6k
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:34Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewFnliiRnWFfNFU87ngX8DdjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDOFEJlh2jC/KIW94AgEQgDuqxWkVJ0x46qqo0TMOEtsZjlFeG+dzcDJyTph3cf/mcnH+dwQyLygItIe8nKxmdXAIC5GM1iElC/tHtw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:34Z'
    mac: ENC[AES256_GCM,data:CY/gLFKotr/mQchNyXjTfVekAsOshQ59WZ1rIfTM6LXiBEVi4npWYCZTlLfrZGcNpgwRwwRUEkiNdGMb4Xh0HJa/rb8J/4NmSF/c1seKt2k/sjH9QiaAfRmySsJxKaeI6KyqPxcXfxrKPFviQtl4LJELKFHXMJ6sxmS5eT3UPkw=,iv:8+eWJbuEWV0jXCewhqon5Z/SWCU5emPOklUnpyFQY4c=,tag:dbuwMHt/tkhZGWqzZkF9jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
