apiVersion: v1
kind: Secret
metadata:
    name: vpnkit-controller-token-q9rjd
    namespace: kube-system
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:35Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewGNso9B1Utp/Pgrx6s9d9aBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqofMDbco4E+IGiyhAgEQgDsdBXtvcDDUaK7HcwisYMjdYyj6g4DL3KF8zXcI++Wy3XyB/ZXhZIJC4DKjMvLjfdAsX71svCvzwgbE1A==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:35Z'
    mac: ENC[AES256_GCM,data:LgmVZUbstWJBPKviVjq0hK4+hEi3NlzKo/eGjYRFZ7SP1/UCQaVuYR4d6UhXM+4lmybtbkyUzoXM80ndME+1JkroXoiqXx75fHvbPruMQZ2q2kniwjowuTYFEHxLiP4DT4n0fNJklbL419cUOkjvVuOVXs85DYeksuMe/pO2kZk=,iv:azMhHobOOV7cvLI7QH9djNsuz21F7ZExDIJ9eOcof74=,tag:K5qoyrPSA+T+/ZC+w3qvEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
