apiVersion: v1
kind: Secret
metadata:
    name: default-token-6vq2r
    namespace: kube-public
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:466238317701:key/463d7832-ad9c-4bef-aff3-55ae1151ad4e
        created_at: '2020-12-21T19:27:31Z'
        enc: AQICAHh830vnfN69pZ+NO1gJQHPbqIT0j28cyi4vySNIBONcewFeCmbcjJBgXT+b1n4QQkO3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1t5t+2QX/GlZ2j5ZAgEQgDv7PhQ2AD0ikb5LDxsfF7mTErrZs7IKePDG8h3j8de3zpJoohJ5y75Ub3Jb0MqFxti8P/93uCNjw9QJvg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-21T19:27:31Z'
    mac: ENC[AES256_GCM,data:gYa3rcUMAjuAM71Lq3vTLVy4atb+kl5JVcS5l5b+aClfd4HXTgCDbSBg/YFz2A/Pvhf12IwSiXjhBj4f8JMlAGYyQOJtdQ4LXABAP529vQuWfkaiLUGl9CggRiU7i9LSHSrk7WGwei2Oyd3OgAqRErwhAEUeKOf64C7KiHuZJJo=,iv:AU9hKzweXFIIpF9tGOvnBjUFliYhjxKbfKM/kjGP6gw=,tag:0b8j2BLeGsCUsWhmtOmiRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
